services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - net-backend-mongo

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/src/.env
    depends_on:
      - mongodb
    networks:
      - net-backend-mongo
      - net-backend-frotend
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frotend
    depends_on:
      - backend
    networks:
      - net-backend-frotend

volumes:
  mongo-data:

networks:
  net-backend-frotend:
    driver: bridge
  net-backend-mongo:
    driver: bridge