apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-hello
  template:
    metadata:
      labels:
        app: k8s-hello
    spec:
      containers:
      - name: hello
        image: josejesusguzman/k8s-hello:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000