services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=Server=LAPTOP-N3MMEJIH\\MYSERVER;Database=Starbucks;User Id=josejesus;Password=5f6g7h8j9k0l.
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=5f6g7h8j9k0l.
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
  

volumes:
  mssqldata: