apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-hello
  template:
    metadata:
      labels:
        app: k8s-hello
    spec:
      containers:
      - name: hello
        image: josejesusguzman/k8s-hello:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:  
        - name: GREETING
          valueFrom:
            configMapKeyRef:
              name: hello-secret
              key: GREETING
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: API_TOKEN
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10